/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelisIndexRouteImport } from './routes/panelis/index'
import { Route as PanelisSpeakerIdRouteImport } from './routes/panelis/$speakerId'
import { Route as EpizodEpisodeIdRouteImport } from './routes/epizod/$episodeId'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelisIndexRoute = PanelisIndexRouteImport.update({
  id: '/panelis/',
  path: '/panelis/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelisSpeakerIdRoute = PanelisSpeakerIdRouteImport.update({
  id: '/panelis/$speakerId',
  path: '/panelis/$speakerId',
  getParentRoute: () => rootRouteImport,
} as any)
const EpizodEpisodeIdRoute = EpizodEpisodeIdRouteImport.update({
  id: '/epizod/$episodeId',
  path: '/epizod/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/privacy': typeof PrivacyRoute
  '/epizod/$episodeId': typeof EpizodEpisodeIdRoute
  '/panelis/$speakerId': typeof PanelisSpeakerIdRoute
  '/panelis': typeof PanelisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/privacy': typeof PrivacyRoute
  '/epizod/$episodeId': typeof EpizodEpisodeIdRoute
  '/panelis/$speakerId': typeof PanelisSpeakerIdRoute
  '/panelis': typeof PanelisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/privacy': typeof PrivacyRoute
  '/epizod/$episodeId': typeof EpizodEpisodeIdRoute
  '/panelis/$speakerId': typeof PanelisSpeakerIdRoute
  '/panelis/': typeof PanelisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontak'
    | '/privacy'
    | '/epizod/$episodeId'
    | '/panelis/$speakerId'
    | '/panelis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontak'
    | '/privacy'
    | '/epizod/$episodeId'
    | '/panelis/$speakerId'
    | '/panelis'
  id:
    | '__root__'
    | '/'
    | '/kontak'
    | '/privacy'
    | '/epizod/$episodeId'
    | '/panelis/$speakerId'
    | '/panelis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontakRoute: typeof KontakRoute
  PrivacyRoute: typeof PrivacyRoute
  EpizodEpisodeIdRoute: typeof EpizodEpisodeIdRoute
  PanelisSpeakerIdRoute: typeof PanelisSpeakerIdRoute
  PanelisIndexRoute: typeof PanelisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panelis/': {
      id: '/panelis/'
      path: '/panelis'
      fullPath: '/panelis'
      preLoaderRoute: typeof PanelisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panelis/$speakerId': {
      id: '/panelis/$speakerId'
      path: '/panelis/$speakerId'
      fullPath: '/panelis/$speakerId'
      preLoaderRoute: typeof PanelisSpeakerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epizod/$episodeId': {
      id: '/epizod/$episodeId'
      path: '/epizod/$episodeId'
      fullPath: '/epizod/$episodeId'
      preLoaderRoute: typeof EpizodEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontakRoute: KontakRoute,
  PrivacyRoute: PrivacyRoute,
  EpizodEpisodeIdRoute: EpizodEpisodeIdRoute,
  PanelisSpeakerIdRoute: PanelisSpeakerIdRoute,
  PanelisIndexRoute: PanelisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
